# Generated by Django 3.0.5 on 2020-08-17 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ATitle', models.CharField(blank=True, max_length=100, null=True)),
                ('ADetail', models.TextField(blank=True, null=True)),
                ('AImage', models.ImageField(blank=True, null=True, upload_to='adds/')),
                ('ADate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CFacebook', models.CharField(blank=True, max_length=150, null=True)),
                ('CTwitter', models.CharField(blank=True, max_length=150, null=True)),
                ('CTelegram', models.CharField(blank=True, max_length=150, null=True)),
                ('CEmail', models.CharField(blank=True, max_length=150, null=True)),
                ('CAddress', models.CharField(blank=True, max_length=150, null=True)),
                ('CPhone', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NTitle', models.CharField(blank=True, max_length=100, null=True)),
                ('NDetail', models.TextField(blank=True, null=True)),
                ('NImage', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('NDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OTitle', models.CharField(blank=True, max_length=150, null=True)),
                ('ODetail', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QQuestion', models.CharField(max_length=100)),
                ('QAnswer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Success',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STitle', models.CharField(max_length=100)),
                ('SDep', models.CharField(max_length=100)),
                ('SDetail', models.TextField(blank=True, null=True)),
                ('SImage', models.ImageField(blank=True, null=True, upload_to='success/')),
            ],
        ),
        migrations.CreateModel(
            name='NavBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAVName', models.CharField(max_length=50)),
                ('NAVSlug', models.SlugField(blank=True, null=True)),
                ('NAVHasFather', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.NavBar')),
            ],
        ),
        migrations.CreateModel(
            name='MotionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MITitle', models.CharField(default='', max_length=100)),
                ('MIDetail', models.TextField(blank=True, null=True)),
                ('MIImage', models.ImageField(blank=True, null=True, upload_to='motion/')),
                ('MIVisible', models.BooleanField()),
                ('MIRelation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.NavBar')),
            ],
        ),
    ]
