# Generated by Django 3.0.5 on 2020-08-19 09:51

from django.db import migrations
import quilljs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='NAVHtml',
            field=quilljs.fields.RichTextField(blank=True, null=True),
        ),
    ]
