# Generated by Django 3.0.5 on 2020-08-21 07:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_navbar_navhtml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='NAVHtml',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
