# Generated by Django 3.0.7 on 2020-08-22 13:08

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_auto_20200821_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='NShort',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='NAVHtml',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
